
#!/bin/bash
#接oracle_install_3
#oracle账户下运行
#oracle账户执行root权限
source ~/.bash_profile
#监听地址配置
hostname=`grep "HOSTNAME" /etc/sysconfig/network|cut -f2 -d"="`
sudo -s echo "" > /u01/app/oracle/product/11.2.0/db_1/network/admin/listener.ora
sudo -s echo "" > /u01/app/oracle/product/11.2.0/db_1/network/admin/tnsnames.ora
sudo -s cat > /u01/app/oracle/product/11.2.0/db_1/network/admin/listener.ora <<EOF
# listener.ora Network Configuration File: /u01/app/oracle/product/11.2.0/db_1/network/admin/listener.ora
# Generated by Oracle configuration tools.
SID_LIST_LISTENER =
  (SID_LIST =
    (SID_DESC =
      (SID_NAME = PLSExtProc)
      (ORACLE_HOME = /u01/app/oracle/product/11.2.0/db_1)
      (PROGRAM = extproc)
    )
    (SID_DESC =
      (GLOBAL_DBNAME = orcl)
      (ORACLE_HOME = /u01/app/oracle/product/11.2.0/db_1)
      (SID_NAME = orcl)
    )
  )
LISTENER =
  (DESCRIPTION_LIST =
    (DESCRIPTION =
      (ADDRESS = (PROTOCOL = IPC)(KEY = EXTPROC1521))
      (ADDRESS = (PROTOCOL = TCP)(HOST = $hostname)(PORT = 1521))
    )
  )

ADR_BASE_LISTENER = /u01/app/oracle               
EOF
sudo -s cat > /u01/app/oracle/product/11.2.0/db_1/network/admin/tnsnames.ora <<FOE
# tnsnames.ora Network Configuration File: /u01/app/oracle/product/11.2.0/db_1/network/admin/tnsnames.ora
# Generated by Oracle configuration tools.
LISTENER_ORCL =
  (ADDRESS = (PROTOCOL = IPC)(KEY = EXTPROC1521))
ORCL =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = $hostname)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = orcl)
    )
  )
FOE
#开机自启动
sed -i "/ORACLE_HOME_LISTNER=$1/a ORACLE_HOME_LISTNER=/u01/app/oracle/product/11.2.0/db_1" /u01/app/oracle/product/11.2.0/db_1/bin/dbstart
sed -i "/^ORATAB=\/etc\/oratab/a ORATAB=/u01/app/oracle/product/11.2.0/db_1/install/oratab" /u01/app/oracle/product/11.2.0/db_1/bin/dbstart
sudo -s echo "orcl:/u01/app/oracle/product/11.2.0/db_1:Y" >>/u01/app/oracle/product/11.2.0/db_1/install/oratab
sudo -s chmod 700 /etc/rc.d/rc.local
sudo -s echo "su oracle -lc \"/u01/app/oracle/product/11.2.0/db_1/bin/lsnrctl start\"" >>/etc/rc.d/rc.local
sudo -s echo "su oracle -lc \"/u01/app/oracle/product/11.2.0/db_1/bin/dbstart\"" >>/etc/rc.d/rc.local
sudo -s chmod +x /etc/rc.d/rc.local